#ddev-generated
services:
  openapi-mock:
    container_name: ddev-${DDEV_SITENAME}-openapi-mock
    image: ${OPENAPI_MOCK_DOCKER_IMAGE:-muonsoft/openapi-mock:latest}
    labels:
      com.ddev.site-name: ${DDEV_SITENAME}
      com.ddev.approot: ${DDEV_APPROOT}
    volumes:
      - ".:/mnt/ddev_config"
      - "ddev-global-cache:/mnt/ddev-global-cache"
      - ./openapi:/data
    expose:
      - ${OPENAPI_MOCK_PORT:-8080}
    environment:
      - OPENAPI_MOCK_SPECIFICATION_URL=${OPENAPI_MOCK_SPECIFICATION:-https://raw.githubusercontent.com/muonsoft/openapi-mock/refs/heads/master/examples/petstore.yaml}
      - OPENAPI_MOCK_USE_EXAMPLES=${OPENAPI_MOCK_USE_EXAMPLES:-if_present}
      - OPENAPI_MOCK_CORS_ENABLED=${OPENAPI_MOCK_CORS_ENABLED:-true}
      - VIRTUAL_HOST=$DDEV_HOSTNAME
      - HTTP_EXPOSE=${OPENAPI_MOCK_PORT:-8080}:8079
      - HTTPS_EXPOSE=${OPENAPI_MOCK_PORT:-8080}:8080
